version: '3'
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile-web
        ports:
            - "80:9000"
        depends_on:
            - db
    db:
        build:
            context: .
            dockerfile: Dockerfile-db
